version: "3"
services:
  jupyter:
    build: .
    volumes:
      - ./:/home/jovyan/work
    ports:
      - "8888:8888"
      - "8265:8265"
    shm_size: "2gb"
    command: jupyter notebook --NotebookApp.token=''
